#!/usr/bin/env bash

# Stop on first error.
set -e

# current directory
dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

TAG=${TAG:-latest}

docker run --rm --interactive --tty \
  -v "$dir"/../app:/app \
  wrangoler:"$TAG" "$@"