#!/usr/bin/env bash

# Stop on first error.
set -e

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

docker run --rm --interactive --tty \
  -v "$dir"/../logs:/app/logs \
  -v "$dir"/../output:/app/output \
  -v "$dir"/../configs:/app/configs \
  wrangoler:latest