#!/usr/bin/env bash

# Stop on first error.
set -e

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

help() {
  echo "Wrangoler Run Utility"
  echo ""
  echo "Use this utility to compile and run Wrangoler."
  echo ""
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo "  -h, --help        Show this help."
  echo "  -c  --compile     Compile the Wrangoler code."

  exit 0
}

# Defaults
COMPILE=false

# Read Command Line Arguments
while [ "$1" != "" ]; do
  case "$1" in
    -h|--help)
      help
      ;;
    -c|--compile)
      COMPILE=true
      ;;
  esac
  shift
done

###
# Check the user asked to do something
###

if [ "$COMPILE" = "true" ] ; then
  source ./scripts/compile
fi

./main